#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 1
fi

python -m py_compile "$PYFILE"

filename_without_extension=$(basename "$PYFILE" ".py")

compiled_filename="$filename_without_extension.pyc"
mv "__pycache__/$filename_without_extension.cpython-*.pyc" "$compiled_filename"

rm -rf "__pycache__"

echo "Compilation completed. Compiled file: $compiled_filename"

